version: '3.7'

services:
  be:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/myfolder/
    ports:
      - 3000:3000

  docker-db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12121212
    ports:
      - 3306:3306
